EXPERIMENT:
  NAME: ""
  TAG: "dkd,res110,res32,lp 0.0,0.1,0.2,0.3"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "DKD"
  TEACHER: "resnet110"
  STUDENT: "resnet32"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 80
  LR: 0.05
  LR_DECAY_STAGES: [20, 30, 40, 50, 60]
  LR_DECAY_RATE: 0.5
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
DKD:
  BETA: 2.0
